### ISSUE TITLE
0.17 support?

### ISSUE THREAD

**Issue by proProbe** [laszlopandy/elm-console#12]
Hello!
Love your work!
Im here asking if there will be a port over to elm 0.17?

**Comment by laszlopandy** [comment]
I have not looked at updating it yet, but if someone sends a PR I will be happy to review it. If not, I will get to it next week I hope.

**Comment by tiziano88** [comment]
I have started attempting to port the code to 0.17, but I'm a bit stuck with the types in https://github.com/laszlopandy/elm-console/blob/master/src/Console/NativeCom.elm . What should these `Signal`s be converted to?

**Comment by laszlopandy** [comment]
Yes that is the hard part. I believe that NativeCom has to be an effect module because there is stateful information coming in from outside (ie. a `Sub`). Unfortunately the docs for effect modules aren't ready. Until then we have to look at other examples like: https://github.com/elm-lang/websocket/blob/master/src/WebSocket.elm

**Comment by laszlopandy** [comment]
I am starting to think now that this library should not be supported in 0.17. Now that there are effect modules, there should instead be a general `elm-node` library which exposes reading/writing files and console input/output as a particular `Cmd` type. The model that elm-console uses now (sending tasks out ports) doesn't work in 0.17 and this library would have be rewritten anyway.

@proProbe @tiziano88 What will you use this library in elm 0.17? I want to want to continue working on something if it doesn't solve your problem.

**Comment by tiziano88** [comment]
Thanks @laszlopandy , personally I am only looking at using this for running elm tests from command line. If there were another way of doing that, I would actually have no other use cases for this library.

**Comment by laszlopandy** [comment]
https://github.com/elm-community/elm-test#testing-from-the-command-line

**Comment by kgashok** [comment]
[Bogdan](https://gist.github.com/Bogdanp/1613141a4e64330b8d4580f3a54b114d) and I have similar issues in executing tests on the command line. Is that a fix for this?

**Comment by kgashok** [comment]
@tiziano88 ,  @laszlopandy  Fapian and I are noticing similar issues when launching tests from the command line: 
When I run  `node tests.js`, I get the following error: 

```
onDocument: F3(on(document)),
                      ^
ReferenceError: document is not defined
    at /home/ashokb/hero/hello/tests/tests.js:7822:20
    at Object.<anonymous> (/home/ashokb/hero/hello/tests/tests.js:7826:2)
    at Object.<anonymous> (/home/ashokb/hero/hello/tests/tests.js:9484:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

```

**Comment by kgashok** [comment]
@tiziano88 I was able to resolve this by separating out my `model` and `view` components into two separate files, and only including the `model` into the Test elm file.
